### ISSUE TITLE
Custom data types support

### ISSUE THREAD

**Issue by cdcseacave** [awulkiew/graphical-debugging#12]
While I see examples of adding support for new point types, how do we add support for custom geometry types, ex a custom polygon structure?

**Comment by awulkiew** [comment]
There is only basic support for user-defined point types in XML files. In the future all geometry types should be supported but it's not there yet.

For now the only way of adding support for your polygon type is to fork the repository, add your class in the `ExpressionLoader` and build your version of the extension.

I'll treat this issue as feature request.

**Comment by awulkiew** [comment]
@cdcseacave I've implemented a basic support for custom geometries. Could you write some examples of your geometries here?

**Comment by cdcseacave** [comment]
Super!
For ex:
```
template <typename TYPE>
struct Polygon {
   struct Point {
      TYPE x, y;
   };
   std::vector<Point> points;
};
```
A polygon defined as a list of consecutive points, where the last point also connects to the first one.

**Comment by awulkiew** [comment]
Ok, so this would work right now. Do you also use some raw arrays (instead of std::vector) of points or are you storing the coordinates in separate containers (one for X and the other for Y)?

**Comment by cdcseacave** [comment]
In fact I do use custom vectors instead of std::vector, is this a problem?

**Comment by awulkiew** [comment]
But a *pointer* and *size* expressions would be enough to define the container, correct?
Like in case of *.natvis `ArrayItems` defined by `ValuePointer` and `Size`.

**Comment by cdcseacave** [comment]
indeed

**Comment by awulkiew** [comment]
@cdcseacave I released it with [v0.29](https://github.com/awulkiew/graphical-debugging/releases/tag/v0.29). Could you test it? Also see the [examples](https://github.com/awulkiew/graphical-debugging/tree/master/examples).

**Comment by cdcseacave** [comment]
I gave it a try, but I'm not sure I did it right. I have a polygon class using internally a custom vector to store the points, and the points are Eigen matrices, all with template types. Where do I start? Reading the docs, it says no templates are supported. Can you give me an example of how I create a visualizer for this polygon? Do I need to add to XML all 3 classes: point type, vector type and polygon type?

**Comment by awulkiew** [comment]
> it says no templates are supported

What I had in mind is that currently only the identifier is used to distinguish between types so it is not possible to have different definitions for different specialization of a type, e.g. a template 

template <typename T>
struct MyPoint {};

would have only 1 definition based on `MyPoint` identifier. Besides that templates are supported and you also can use template parameters in the expressions, e.g.: $T0, $T1, etc.

> Can you give me an example 

You have to define Eigen matrix as a Point and then your polygon as a Ring (polygon without holes) where Points in the Ring are defined as an Array with Pointer and Size taken from your custom vector. It would be easier if you shared some simplified version of your classes. Let's assume the classes looks like this:

```
namespace Eigen {
namespace internal {
template <typename T, int N>
struct plain_array
{
    T array[N];
};
}
template <typename T, int N>
struct DenseStorage
{
    internal::plain_array<T, N> m_data;
};
template <typename T, int R, int C>
struct Matrix
{
    static const int size = R * C;
    DenseStorage<T, size> m_storage;
};
}

template <typename T>
struct CustomVector
{
    T * m_begin;
    T * m_end;
    T * m_alloc_end;
};

template <typename Point>
struct PolygonWithoutHoles
{
    CustomVector<Point> m_points;
};
```

Then the XML file would look like this:

```
<?xml version="1.0" encoding="utf-8"?>
<GraphicalDebugging>

  <Point Id="Matrix">
    <Coordinates>
      <X>m_storage.m_data.array[0]</X>
      <Y>m_storage.m_data.array[1]</Y>
    </Coordinates>
  </Point>

  <Ring Id="PolygonWithoutHoles">
    <Points>
      <Array>
        <Pointer>m_points.m_begin</Pointer>
        <Size>m_points.m_end - m_points.m_begin</Size>
      </Array>
    </Points>
  </Ring>

</GraphicalDebugging>
```

**Comment by awulkiew** [comment]
@cdcseacave I added missing `Eigen` namespace in the example above. Also, have in mind I didn't test it.

**Comment by cdcseacave** [comment]
It does work, thank you! Looking great! This will be of big help to me.
![image](https://user-images.githubusercontent.com/2802670/74716101-933a3b00-5236-11ea-90cd-2c4b7bdf7928.png)

**Comment by cdcseacave** [comment]
If I have a vector of such polygons, is it possible to draw all of them, or I have to enter them by hand one by one?

**Comment by awulkiew** [comment]
That's great!

> If I have a vector of such polygons...

Currently, only if it's a separate type defined as MultiPolygon (a collection of polygons with holes). So besides your Ring type you'd also need separate Polygon type and MultiPolygon type. If you have such classes in your code then you can.

Plus standard containers (vector, list, set, etc.) of points are handled automatically so containers of any geometry could also be but AFAIR this is not the case now, though I don't remember exactly. Though you probably use your own vector here too.

So I see two additional improvements here:
* MultiGeometry XML entry allowing to define collection of any geometries (you'd probably use this to define a collection of Rings)
* automatic handling of standard containers of any geometry types

I'll leave this issue opened.

**Comment by awulkiew** [comment]
@cdcseacave Both MultiGeometry and user-defined Container type is supported now ([v0.30](https://github.com/awulkiew/graphical-debugging/releases/tag/v0.30)). If you store any known geometry in any known container the extension should display it automatically.

So you should be able to define e.g.:

  <Container Id="MyVector">
    <Array>
      <Pointer>m_first</Pointer>
      <Size>m_last - m_first</Size>
    </Array>
  </Container>

and then use it in your geometries as a `Container` instead of manually set `Array` fields in all of them. Plus if you store any of your geometries in `MyVector` the extension should display all of the geometries stored in it. If you store polygons in a non-general-purpose container but rather in a container designed specifically as a collection of geometries then define it as `MultiGeometry` instead.

**Comment by cdcseacave** [comment]
This does not seem to work, and since you do not support templates, I do not see how can work, as the vector is used for so many different data, not only Polygons.

Apart of this, it would be useful a way to translate the grapth. I found a way to zoom in and out, and using the mouse left button seems to select a region of interest, but I did not find a way to move the graph.

**Comment by awulkiew** [comment]
> This does not seem to work

Do you specify the qualified identifier properly, with all namespaces (e.g. `SEACAVE::TVector`)?

If you don't provide anything for me to reproduce your case I won't be able to verify whether or not something works or not and find bugs if there are any.

> you do not support templates

Templates are supported, otherwise e.g. `std::vector` would not work. Different entries in XML file for the same qualified identifier are not supported. Even if you had specializations but the members were the same it should work. Types that are not supported are like e.g. C++03 implementation of `std::vector<bool>` because the elements are accessed differently than e.g. in `std::vector<int>`, `std::vector<double>` or `std::vector<Point>`.

> I do not see how can work, as the vector is used for so many different data

It doesn't matter as long as the members of the vector are the same.
Do you have many [specializations](https://en.cppreference.com/w/cpp/language/template_specialization) of your vector?
Do you [specialize](https://en.cppreference.com/w/cpp/language/template_specialization) vector for each geometry?
Do you have different members in each of them?
If no, then the extension should get the element type (e.g. from `*my_vector.m_first`) and if this type is a geometry treat it as such. I tested standard containers like `std::vector`, `std::list` or `std::set` and my additional test containers. The fact that they are templates is not important. So it should work for your containers as well unless the definition is wrong or there is a bug exposed by your specific case. But I can't verify which one of the two possibilities is it without your example.

The "specialization" we're talking about is [this language feature](https://en.cppreference.com/w/cpp/language/template_specialization), right?

And to clarify, when I'm talking about the "identifier" I have [qualified identifier](https://en.cppreference.com/w/cpp/language/identifiers#Qualified_identifiers) in mind.

> Apart of this, it would be useful a way to translate the graph.

There is no way right now. It's a different issue. Btw, I accept pull requests. :)

**Comment by cdcseacave** [comment]
Thanks for all your help. I'm also quite busy and I can not contribute right now.
This is the vector class:
```
https://github.com/cdcseacave/openMVS/blob/master/libs/Common/List.h
```
and this is the specialized I added to your XML:
```
<?xml version="1.0" encoding="utf-8"?>
<GraphicalDebugging>
  <Point Id="Eigen::Matrix">
    <Coordinates>
      <X>m_storage.m_data.array[0]</X>
      <Y>m_storage.m_data.array[1]</Y>
    </Coordinates>
  </Point>

  <Ring Id="SEACAVE::TPolygon">
    <Points>
      <Array>
        <Pointer>points._vector</Pointer>
        <Size>points._size</Size>
      </Array>
    </Points>
  </Ring>
  
  <Container Id="SEACAVE::cList">
    <Array>
      <Pointer>_vector</Pointer>
      <Size>_size</Size>
    </Array>
  </Container>
</GraphicalDebugging>
```

**Comment by awulkiew** [comment]
@cdcseacave I just tried it (v0.30) with VS2017 in both x64 and x86, and it works for me.

Specifically this program:
```
#include <cassert>
#include <cstdint>
#include <vector>
#define STCALL
#define RESTRICT
#define DECLARE_NO_INDEX(T) 0
#define ASSERT(C) assert(C)
#include "List.h"

namespace Eigen {
namespace internal {
template <typename T, int N>
struct plain_array
{
    T array[N];
};
}
template <typename T, int N>
struct DenseStorage
{
    internal::plain_array<T, N> m_data;
};
template <typename T, int R, int C>
struct Matrix
{
    static const int size = R * C;
    DenseStorage<T, size> m_storage;
};
}

namespace SEACAVE
{
    template <typename T>
    struct TPolygon
    {
        typedef Eigen::Matrix<T, 1, 2> point_type;
        cList<point_type> points;
    };
}

template <typename T, typename V1, typename V2>
inline void push_back(SEACAVE::TPolygon<T> & poly, V1 x, V2 y)
{
    Eigen::Matrix<T, 1, 2> pt;
    pt.m_storage.m_data.array[0] = x;
    pt.m_storage.m_data.array[1] = y;
    poly.points.push_back(pt);
}

int main()
{
    using namespace SEACAVE;
    TPolygon<float> poly1;
    TPolygon<float> poly2;
    cList<TPolygon<float> > polys;

    ::push_back(poly1, 0, 0);
    ::push_back(poly1, 0, 1);
    ::push_back(poly1, 1, 1);
    ::push_back(poly1, 1, 0);
    ::push_back(poly1, 0, 0);

    ::push_back(poly2, 2, 2);
    ::push_back(poly2, 2, 3);
    ::push_back(poly2, 3, 3);
    ::push_back(poly2, 3, 2);
    ::push_back(poly2, 2, 2);

    polys.push_back(poly1);
    polys.push_back(poly2);

    return 0;
}
```

![aaa](https://user-images.githubusercontent.com/1226951/75115949-e6abef00-5663-11ea-8574-202dfc54ef5f.png)

Do you see something wrong in what I'm doing?
Did the extension update correctly to v0.30?
Could you check if this code works for you?

**Comment by awulkiew** [comment]
@cdcseacave Btw, I just found a bug causing user-defined containers to expect and use the first template argument as the type of the element. I mention it in case it might lead you to the cause of your problem, even though your `cList<>` should not be affected. This could manifest e.g. if you decided to define `TPolygon<>` as a Container, because `TPolygon<>` contains Points of some sort but the first template argument is coordinate type.

**Comment by cdcseacave** [comment]
I confirm, it works, I must have forgot to update to latest version cause I reinstalled and it worked directly. Thank you!

**Comment by awulkiew** [comment]
I'm glad that it works for you. Thanks for good proposals!
