### ISSUE TITLE
IList isn't supported in .Net

### ISSUE THREAD

**Issue by pybride** [awulkiew/graphical-debugging#16]
Hi,
It's a useful tool, but I didn't understand at first why I didn't have any plot. 

It seems that IList isn't supported, even if the object is really an standard List. In the screenshot below, baseline don't display anything, but temp works fine (temp = baseline.ToList())

![image](https://user-images.githubusercontent.com/13061922/80949603-989a3100-8df4-11ea-9807-810405968ab2.png)

**Comment by awulkiew** [comment]
Hi, indeed more C# types should be supported. Thanks for the suggestion.

**Comment by awulkiew** [comment]
Btw, a workaround for this would be to cast `IList` to `List` so to instead of `baseline` write `((System.Collections.Generic.List<Camag.Platypus.CommonClient3D.ChartData>)baseline)`. It's possible it'd work without the namespaces too, so: `((List<Camag.Platypus.CommonClient3D.ChartData>)baseline)` or `((List<ChartData>)baseline)`.

**Comment by awulkiew** [comment]
Added support for all base classes of known types in C# in v0.32.
