### ISSUE TITLE
Not work user rect type

### ISSUE THREAD

**Issue by Ok23** [awulkiew/graphical-debugging#22]
In xml:
```xml
  <Box Id="Rect" CoordinateSystem="Cartesian" Unit="None">
    <Coordinates>
      <MinX>left</MinX> <!-- or <Left> or <MaxX> or <Right> -->
      <MinY>top</MinY> <!-- or <Bottom> or <MaxY> or <Top> -->
      <Width>width</Width>
      <Height>height</Height>
    </Coordinates>
  </Box>
```
code:
```cpp
struct Rect
{
public:
	float left, top, width, height;
};
```
I tried different labels in xml for coordinates as in example, but not successfully.

**Comment by Ok23** [comment]
XML markdown not show in this

**Comment by Ok23** [comment]
Maybe need to restart an IDE for updating defenitions? I restart only debug process

**Comment by awulkiew** [comment]
If you have `width` and `height` you should use `<CoordinatesDimensions>` instead of `<Coordinates>`, see:
https://github.com/awulkiew/graphical-debugging/blob/master/examples/cpp.xml#L123

It should be not needed to restart the IDE. The definitions should be updated just before the geometry is drawn as long as the XML file was modified.

**Comment by Ok23** [comment]
Thanks, but what the difference between CoordinatesDimensions and Coordinates?

**Comment by awulkiew** [comment]
The former is defined by location and dimensions (e.g. for X axis it can be `left` and `width` or `right` and `width`) and the latter is defined by 4 coordinates (e.g. for X axis it has to be `left` and `right`). I called them differently because technically `width` and `height` are not coordinates.

**Comment by Ok23** [comment]
Thanks
